name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    # - run: NODE_CONFIG=${ENTERPRISE_CONFIG} node .
    #   env:
    #     CI: true
    #     ENTERPRISE_CONFIG: ${{ secrets.ENTERPRISE_CONFIG }}
    - run: NODE_CONFIG=${ENTERPRISE_CONFIG} npm test -- --runInBand
      env:
        CI: true
        ENTERPRISE_CONFIG: ${{ secrets.ENTERPRISE_CONFIG }}